name: sikasir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  avatar_glow: 2.0.2
  cloud_firestore: ^4.3.1
  convex_bottom_bar: ^3.1.0+1
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.8
  dropdown_button2: ^1.9.2
  expandable: ^5.0.1
  firebase_auth: ^4.1.5
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_multi_formatter: ^2.10.0
  get: 4.6.5
  get_storage: ^2.0.3
  image_picker: ^0.8.6
  introduction_screen: ^3.1.2
  lottie: ^2.1.0
  sliding_up_panel: ^2.0.0+1
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  fl_chart: ^0.36.1
  provider: ^5.0.0
  data_table_2: ^2.0.3

dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  assets:
    - assets/lottie/
    - assets/logo/
    - assets/background/
    - assets/icons/
  uses-material-design: true
