name: sikasir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  avatar_glow: 2.0.2
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.9.2
  firebase_auth: ^4.1.5
  firebase_core: ^2.4.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  get: 4.6.5
  get_storage: ^2.0.3
  image_picker: ^0.8.6
  intl: ^0.18.0
  introduction_screen: ^3.1.2
  lottie: ^2.1.0
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/ico.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  assets:
    - assets/lottie/
    - assets/logo/
    - assets/background/
  uses-material-design: true
