// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo06EcKc4XkvMkTwsFlo7m0A0sxjybtfc',
    appId: '1:544523707198:web:d5c5121c01c952d67f426f',
    messagingSenderId: '544523707198',
    projectId: 'sikasir-rony',
    authDomain: 'sikasir-rony.firebaseapp.com',
    databaseURL: 'https://sikasir-rony-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sikasir-rony.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBENf0qJ4kbi4BtEVfwm1TAfU-r4QCxucY',
    appId: '1:544523707198:android:755b1ba7eb88f93d7f426f',
    messagingSenderId: '544523707198',
    projectId: 'sikasir-rony',
    databaseURL: 'https://sikasir-rony-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sikasir-rony.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFT1MZrJNVmsCv7FmMBujSkwVsRwLxGrQ',
    appId: '1:544523707198:ios:fad933c7e5c0ed8c7f426f',
    messagingSenderId: '544523707198',
    projectId: 'sikasir-rony',
    databaseURL: 'https://sikasir-rony-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sikasir-rony.appspot.com',
    androidClientId: '544523707198-bhd6gs9bg6snvhkb1oc8fh39q97v7pqe.apps.googleusercontent.com',
    iosClientId: '544523707198-ghkmaiod6uctp8o8sqnqjte2joh9lkif.apps.googleusercontent.com',
    iosBundleId: 'com.ta.sikasir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFT1MZrJNVmsCv7FmMBujSkwVsRwLxGrQ',
    appId: '1:544523707198:ios:fad933c7e5c0ed8c7f426f',
    messagingSenderId: '544523707198',
    projectId: 'sikasir-rony',
    databaseURL: 'https://sikasir-rony-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sikasir-rony.appspot.com',
    androidClientId: '544523707198-bhd6gs9bg6snvhkb1oc8fh39q97v7pqe.apps.googleusercontent.com',
    iosClientId: '544523707198-ghkmaiod6uctp8o8sqnqjte2joh9lkif.apps.googleusercontent.com',
    iosBundleId: 'com.ta.sikasir',
  );
}
