part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const INTRODUCTION = _Paths.INTRODUCTION;
  static const LOGIN = _Paths.LOGIN;
  static const ADD_PRODUK = _Paths.ADD_PRODUK;
  static const ADD_PEGAWAI = _Paths.ADD_PEGAWAI;
  static const NEW_PASSWORD = _Paths.NEW_PASSWORD;
  static const ADD_SUPPLIER = _Paths.ADD_SUPPLIER;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const PROFILE = _Paths.PROFILE;
  static const UPDATE_PROFILE = _Paths.UPDATE_PROFILE;
  static const UPDATE_PASSWORD = _Paths.UPDATE_PASSWORD;
  static const KERANJANG = _Paths.KERANJANG;
  static const TRANSAKSI_PENJUALAN = _Paths.TRANSAKSI_PENJUALAN;
  static const HOME_PEGAWAI = _Paths.HOME_PEGAWAI;
  static const ALL_PEGAWAI = _Paths.ALL_PEGAWAI;
  static const DETAIL_PEGAWAI = _Paths.DETAIL_PEGAWAI;
  static const LAPORAN = _Paths.LAPORAN;
  static const HOME_PRODUK = _Paths.HOME_PRODUK;
  static const DETAIL_PRODUK = _Paths.DETAIL_PRODUK;
  static const UPDATE_PRODUCT = _Paths.UPDATE_PRODUCT;
  static const HOME_SUPPLIER = _Paths.HOME_SUPPLIER;
  static const DETAIL_SUPPLIER = _Paths.DETAIL_SUPPLIER;
  static const HOME_TOKO = _Paths.HOME_TOKO;
  static const ADD_TOKO = _Paths.ADD_TOKO;
  static const UPDATE_TOKO = _Paths.UPDATE_TOKO;
  static const DETAIL_TOKO = _Paths.DETAIL_TOKO;
  static const HOME_LAPORAN = _Paths.HOME_LAPORAN;
  static const DETAIL_TRANSAKSI = _Paths.DETAIL_TRANSAKSI;
  static const UPDATE_KERANJANG = _Paths.UPDATE_KERANJANG;
  static const PEMBELIAN_PRODUK = _Paths.PEMBELIAN_PRODUK;
  static const HOME_PEMBELIAN = _Paths.HOME_PEMBELIAN;
  static const ADD_PEMBELIAN = _Paths.ADD_PEMBELIAN;
  static const TRANSAKSI_SELESAI = _Paths.TRANSAKSI_SELESAI;
  static const RIWAYAT_TRANSAKSI = _Paths.RIWAYAT_TRANSAKSI;
  static const SETTINGS = _Paths.SETTINGS;
  static const DETAIL_RIWAYAT = _Paths.DETAIL_RIWAYAT;
  static const LAPORAN_RANGKUMAN = _Paths.LAPORAN_RANGKUMAN;
  static const LAPORAN_RINGKASAN = _Paths.LAPORAN_RINGKASAN;
  static const LAPORAN_PRODUK = _Paths.LAPORAN_PRODUK;
  static const LAPORAN_PEMBELIAN = _Paths.LAPORAN_PEMBELIAN;
  static const LAPORAN_PENJUALAN = _Paths.LAPORAN_PENJUALAN;
  static const LAPORAN_PEGAWAI = _Paths.LAPORAN_PEGAWAI;
  static const BLUE_THERMA_PRINT = _Paths.BLUE_THERMA_PRINT;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const INTRODUCTION = '/introduction';
  static const LOGIN = '/login';
  static const ADD_PRODUK = '/add-produk';
  static const ADD_PEGAWAI = '/add-pegawai';
  static const NEW_PASSWORD = '/new-password';
  static const ADD_SUPPLIER = '/add-supplier';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const PROFILE = '/profile';
  static const UPDATE_PROFILE = '/update-profile';
  static const UPDATE_PASSWORD = '/update-password';
  static const KERANJANG = '/keranjang';
  static const TRANSAKSI_PENJUALAN = '/transaksi-penjualan';
  static const HOME_PEGAWAI = '/home-pegawai';
  static const ALL_PEGAWAI = '/all-pegawai';
  static const DETAIL_PEGAWAI = '/detail-pegawai';
  static const LAPORAN = '/laporan';
  static const HOME_PRODUK = '/home-produk';
  static const DETAIL_PRODUK = '/detail-produk';
  static const UPDATE_PRODUCT = '/update-product';
  static const HOME_SUPPLIER = '/home-supplier';
  static const DETAIL_SUPPLIER = '/detail-supplier';
  static const HOME_TOKO = '/home-toko';
  static const ADD_TOKO = '/add-toko';
  static const UPDATE_TOKO = '/update-toko';
  static const DETAIL_TOKO = '/detail-toko';
  static const HOME_LAPORAN = '/home-laporan';
  static const DETAIL_TRANSAKSI = '/detail-transaksi';
  static const UPDATE_KERANJANG = '/update-keranjang';
  static const PEMBELIAN_PRODUK = '/pembelian-produk';
  static const HOME_PEMBELIAN = '/home-pembelian';
  static const ADD_PEMBELIAN = '/add-pembelian';
  static const TRANSAKSI_SELESAI = '/transaksi-selesai';
  static const RIWAYAT_TRANSAKSI = '/riwayat-transaksi';
  static const SETTINGS = '/settings';
  static const DETAIL_RIWAYAT = '/detail-riwayat';
  static const LAPORAN_RANGKUMAN = '/laporan-rangkuman';
  static const LAPORAN_RINGKASAN = '/laporan-ringkasan';
  static const LAPORAN_PRODUK = '/laporan-produk';
  static const LAPORAN_PEMBELIAN = '/laporan-pembelian';
  static const LAPORAN_PENJUALAN = '/laporan-penjualan';
  static const LAPORAN_PEGAWAI = '/laporan-pegawai';
  static const BLUE_THERMA_PRINT = '/blue-therma-print';
}
